name: XOR (train with SGD)

hidden: 2
hidden_act: sigmoid
out_act: sigmoid
epochs: 5000
learning_rate: 0.7
seed: 2

examples:
  - {x: [0, 0], y: [0]}
  - {x: [0, 1], y: [1]}
  - {x: [1, 0], y: [1]}
  - {x: [1, 1], y: [0]}
